### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by yoelfme** [gomodule/redigo#425]
Hi, we started to use *redigo* in our application, and everything works fine with low traffic but when we started to receive a lot of traffic we receive an error: `panic: runtime error: slice bounds out of range`, and these are the logs that we are seeing:

```shell
goroutine 687 [running]:
bufio.(*Reader).ReadSlice(0xc0023716e0, 0x77670a, 0xc0020a5118, 0xc0020a5108, 0x47eb9d, 0xc004291a80, 0xc004d08000)
	/usr/local/go/src/bufio/bufio.go:331 +0x22e
github.com/gomodule/redigo/redis.(*conn).readLine(0xc000179c20, 0x0, 0xc0020a51a0, 0x521b36, 0xc004291a80, 0x0)
	/go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:431 +0x38
github.com/gomodule/redigo/redis.(*conn).readReply(0xc000179c20, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:504 +0x2f
github.com/gomodule/redigo/redis.(*conn).DoWithTimeout(0xc000179c20, 0x0, 0x75f745, 0x3, 0xc001fb23c0, 0x1, 0x1, 0x10, 0xc001fb23c0, 0x4ba41e, ...)
	/go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:665 +0x15d
github.com/gomodule/redigo/redis.(*conn).Do(0xc000179c20, 0x75f745, 0x3, 0xc001fb23c0, 0x1, 0x1, 0x412098, 0x10, 0x6ef220, 0x3c)
	/go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:616 +0x73
github.com/gomodule/redigo/redis.(*activeConn).Do(0xc0039e00a0, 0x75f745, 0x3, 0xc001fb23c0, 0x1, 0x1, 0x1a, 0x0, 0x0, 0x519bd1)
	/go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:447 +0xe4
yalochat.com/notification-sender/internal/app/notification-sender/helpers.GetBotByIDFromRedis(0xc001fe475c, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/yalochat.com/notification-sender/internal/app/notification-sender/helpers/redis.go:80 +0x1fa
yalochat.com/notification-sender/internal/app/notification-sender/helpers.GetBotByID(0xc001fe475c, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/yalochat.com/notification-sender/internal/app/notification-sender/helpers/bot.go:8 +0x91
yalochat.com/notification-sender/internal/app/notification-sender/senders.(*Whatsapp).SendMessages(0xc00014a000, 0xc001fe475c, 0x3, 0xc001ffe420, 0x1, 0x4, 0xc001fe4738, 0x3, 0xc0018ae000, 0xc0018b6228, ...)
	/go/src/yalochat.com/notification-sender/internal/app/notification-sender/senders/whatsapp.go:83 +0x50
created by yalochat.com/notification-sender/internal/app/notification-sender/consumers.(*NotificationSender).ProcessNotifications
	/go/src/yalochat.com/notification-sender/internal/app/notification-sender/consumers/whatsapp.go:62 +0x2f3
```

and this is how we implement redigo

```golang
var conn redis.Conn
var pool *redis.Pool

func init() {
	redisHost := os.Getenv("REDIS_HOST")
	pool = newPool(redisHost)
	conn = pool.Get()
	defer conn.Close()
	err := ping(conn)
	if err != nil {
		panic(err)
	}
}

func newPool(host string) *redis.Pool {
	connectionString := fmt.Sprintf("%s:6379", host)
	return &redis.Pool{
		// Maximum number of idle connections in the pool.
		MaxIdle: 10,
		// Max number of connections.
		MaxActive: 1000,
		// Time to close a idle connection in the pool.
		IdleTimeout: time.Second * 60,
		// Dial is an application supplied function for creating and
		// configuring a connection.
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", connectionString)
			if err != nil {
				panic(err.Error())
			}
			return c, err
		},
	}
}
```

and this is a function where we use the pool:

```golang
// GetBotByIDFromRedis get information about a bot that previously we stored at Redis
func GetBotByIDFromRedis(botID string) (Bot, bool) {
	conn = pool.Get()
	defer conn.Close()

	var bot Bot
	botKey := fmt.Sprintf("%s:%s", keyPreffix, botID)
	data, err := redis.String(conn.Do("GET", botKey))
	if err == redis.ErrNil {
		return bot, false
	} else if err != nil {
		return bot, false
	}

	err = json.Unmarshal([]byte(data), &bot)

	if err != nil {
		return bot, false
	}

	return bot, true
}
```
and we call that function inside of a **goroutine**

**Comment by propertyscott** [comment]
Check for [data races](https://golang.org/doc/articles/race_detector.html) in the application.

**Comment by yoelfme** [comment]
hi @propertyscott, thanks for your response, yep I saw the `data races` and we were closing the connection that other `goroutines` were using, I'm no longer using goroutines, but do you have any examples about how to use `redigo` with  `goroutines`

**Comment by propertyscott** [comment]
The Pool documentation describes how to use Redigo in multiple goroutines. See also the documentation on [concurrency](https://godoc.org/github.com/gomodule/redigo/redis#hdr-Concurrency).

**Comment by jensenjin** [comment]
+1

**Comment by Fishbubble** [comment]
+1

**Comment by stephenandwood** [comment]
@Fishbubble   Fix the data race in your application.

**Comment by zphilin** [comment]
@yoelfme have you solved the problem by use redigo with goroutines?

**Comment by stevenh** [comment]
The way to ensure this works is to use a pool and have each goroutine / operation call 
```go
c := pool.Get()
defer c.Close()

// process using c...
```

**Comment by longshen123** [comment]
Would you like to ask if there is a specific answer to this question? I also encountered this mistake

**Comment by longshen123** [comment]
> 

我看up主就是用的连接池，但是报错了，还有什么别的方法吗

**Comment by stevenh** [comment]
Only use a connection from the pool in one `goroutine`, don't share it across multiple.

**Comment by longshen123** [comment]
I also want to ask if different connections in the connection pool will share the buffer pool of bufer. IO. This is the cause of the problem

> 仅在一个池中使用一个连接`goroutine`，不要跨多个共享它。

**Comment by stevenh** [comment]
Nope each connection owns its data.

**Comment by longshen123** [comment]
> Nope each connection owns its data.

ok, thanks
