### ISSUE TITLE
Pubsub Pool connection close() goroutines leaks

### ISSUE THREAD

**Issue by Marsyyh** [gomodule/redigo#464]
Goroutine leaks when close on pubsub pool connection

go version go1.13.4 linux/amd64
github.com/gomodule/redigo v2.0.0+incompatible

The issue occurs when I try to close and get connection multiple times in a short time period ( 10 times per 1 second ). It will have 3 or 4 goroutines hangs.

Also, I did the data race checks, no data race

here is my code
```go
type source struct {
	conn rd.PubSubConn
	q    chan struct{}
}

func (s *source) Subscribe(topic string) (<-chan []byte, error) {
	if err := s.conn.Subscribe(topic); err != nil {
		return nil, err
	}

	ch := make(chan []byte)

	go func() {
		for {
			select {
			case <-s.q:
				close(ch)
				s.conn.Close()
				return
			default:
				switch v := s.conn.Receive().(type) {
				case rd.Message:
					ch <- v.Data
				default:
					continue
				}
			}
		}
	}()

	return ch, nil
}

func (s *source) Stop() {
	s.q <- struct{}{}
}
```

Here is the gops tool result I used to find goroutine stack

```
goroutine 187 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fe57165e478, 0x72, 0xe63cc0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000112698, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000112680, 0xc00025d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x253
net.(*netFD).Read(0xc000112680, 0xc00025d000, 0x1000, 0x1000, 0x1000, 0x1000, 0x47)
        /usr/local/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc000010048, 0xc00025d000, 0x1000, 0x1000, 0x0, 0x0, 0x47)
        /usr/local/go/src/net/net.go:184 +0xa1
bufio.(*Reader).fill(0xc0000caf60)
        /usr/local/go/src/bufio/bufio.go:100 +0x19a
bufio.(*Reader).ReadSlice(0xc0000caf60, 0xc00011260a, 0x0, 0x0, 0x4274a0, 0x0, 0x18)
        /usr/local/go/src/bufio/bufio.go:359 +0x96
github.com/gomodule/redigo/redis.(*conn).readLine(0xc0000d5d60, 0x0, 0x0, 0xc0003cfc68, 0x4350ac, 0x4274a0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:431 +0x5a
github.com/gomodule/redigo/redis.(*conn).readReply(0xc0000d5d60, 0x1, 0x1, 0xc000032090, 0x0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:504 +0x51
github.com/gomodule/redigo/redis.(*conn).DoWithTimeout(0xc0000d5d60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x474280, 0xc0001f8300, 0xc0003cfe18, ...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:652 +0x40e
github.com/gomodule/redigo/redis.(*conn).Do(0xc0000d5d60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4119f0, 0x7fe538032048)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:616 +0xa4
github.com/gomodule/redigo/redis.(*activeConn).Close(0xc00033e3a0, 0xc00009a7e0, 0xce8a01)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:427 +0x1da
github.com/gomodule/redigo/redis.PubSubConn.Close(...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pubsub.go:58
streaming-go/source/redis.(*source).Subscribe.func1(0xc00033e3c0, 0xc00009a840)
        /streaming-go/source/redis/redis.go:63 +0x25a
created by streaming-go/source/redis.(*source).Subscribe
        /streaming-go/source/redis/redis.go:58 +0x17a

goroutine 205 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fe57165e548, 0x72, 0xe63cc0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001b8218, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001b8200, 0xc0001fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x253
net.(*netFD).Read(0xc0001b8200, 0xc0001fb000, 0x1000, 0x1000, 0x1000, 0x1000, 0x47)
        /usr/local/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc0003ac008, 0xc0001fb000, 0x1000, 0x1000, 0x0, 0x0, 0x47)
        /usr/local/go/src/net/net.go:184 +0xa1
bufio.(*Reader).fill(0xc0000ca5a0)
        /usr/local/go/src/bufio/bufio.go:100 +0x19a
bufio.(*Reader).ReadSlice(0xc0000ca5a0, 0xc0001b820a, 0x0, 0x0, 0x4274a0, 0x0, 0x18)
        /usr/local/go/src/bufio/bufio.go:359 +0x96
github.com/gomodule/redigo/redis.(*conn).readLine(0xc0001eabe0, 0x0, 0x0, 0xc0002e4c68, 0x4350ac, 0x4274a0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:431 +0x5a
github.com/gomodule/redigo/redis.(*conn).readReply(0xc0001eabe0, 0x1, 0x1, 0xc0001d2cd0, 0x0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:504 +0x51
github.com/gomodule/redigo/redis.(*conn).DoWithTimeout(0xc0001eabe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x474280, 0xc0001f8300, 0xc0002e4e18, ...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:652 +0x40e
github.com/gomodule/redigo/redis.(*conn).Do(0xc0001eabe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4119f0, 0x7fe544011bd8)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:616 +0xa4
github.com/gomodule/redigo/redis.(*activeConn).Close(0xc00033e340, 0xc00009a300, 0xce8a01)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:427 +0x1da
github.com/gomodule/redigo/redis.PubSubConn.Close(...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pubsub.go:58
streaming-go/source/redis.(*source).Subscribe.func1(0xc00033e360, 0xc00009a5a0)
        /streaming-go/source/redis/redis.go:63 +0x25a
created by streaming-go/source/redis.(*source).Subscribe
        /streaming-go/source/redis/redis.go:58 +0x17a

goroutine 175 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fe57165e7b8, 0x72, 0xe63cc0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001b8398, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001b8380, 0xc000115000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x253
net.(*netFD).Read(0xc0001b8380, 0xc000115000, 0x1000, 0x1000, 0x1000, 0x1000, 0xa0)
        /usr/local/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc000010038, 0xc000115000, 0x1000, 0x1000, 0xc00011501b, 0xc0002e59c8, 0x470774)
        /usr/local/go/src/net/net.go:184 +0xa1
bufio.(*Reader).fill(0xc0000ca840)
        /usr/local/go/src/bufio/bufio.go:100 +0x19a
bufio.(*Reader).ReadSlice(0xc0000ca840, 0xc0001b830a, 0x0, 0x0, 0x4274a0, 0x0, 0x18)
        /usr/local/go/src/bufio/bufio.go:359 +0x96
github.com/gomodule/redigo/redis.(*conn).readLine(0xc0000d5c20, 0x0, 0x0, 0xc0002e5c68, 0x4350ac, 0x4274a0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:431 +0x5a
github.com/gomodule/redigo/redis.(*conn).readReply(0xc0000d5c20, 0x1, 0x1, 0xc0001d31c0, 0x0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:504 +0x51
github.com/gomodule/redigo/redis.(*conn).DoWithTimeout(0xc0000d5c20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x474280, 0xc0001f8300, 0xc0002e5e18, ...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:652 +0x40e
github.com/gomodule/redigo/redis.(*conn).Do(0xc0000d5c20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4119f0, 0x7fe534012208)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:616 +0xa4
github.com/gomodule/redigo/redis.(*activeConn).Close(0xc00000e3a0, 0xc000036120, 0xce8a01)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:427 +0x1da
github.com/gomodule/redigo/redis.PubSubConn.Close(...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pubsub.go:58
streaming-go/source/redis.(*source).Subscribe.func1(0xc00000e3c0, 0xc000036180)
        /streaming-go/source/redis/redis.go:63 +0x25a
created by streaming-go/source/redis.(*source).Subscribe
        /streaming-go/source/redis/redis.go:58 +0x17a

goroutine 220 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fe57165e208, 0x72, 0xe63cc0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000112098, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000112080, 0xc000171000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x253
net.(*netFD).Read(0xc000112080, 0xc000171000, 0x1000, 0x1000, 0x1000, 0x1000, 0xa0)
        /usr/local/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc00039c000, 0xc000171000, 0x1000, 0x1000, 0xc00017101b, 0xc0002e39c8, 0x470774)
        /usr/local/go/src/net/net.go:184 +0xa1
bufio.(*Reader).fill(0xc0004f4120)
        /usr/local/go/src/bufio/bufio.go:100 +0x19a
bufio.(*Reader).ReadSlice(0xc0004f4120, 0xc00011200a, 0x0, 0x0, 0x4274a0, 0x0, 0x18)
        /usr/local/go/src/bufio/bufio.go:359 +0x96
github.com/gomodule/redigo/redis.(*conn).readLine(0xc0000d4dc0, 0x0, 0x0, 0xc0002e3c68, 0x4350ac, 0x4274a0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:431 +0x5a
github.com/gomodule/redigo/redis.(*conn).readReply(0xc0000d4dc0, 0x1, 0x1, 0xc0000a52c0, 0x0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:504 +0x51
github.com/gomodule/redigo/redis.(*conn).DoWithTimeout(0xc0000d4dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x474280, 0xc0001f8300, 0xc0002e3e18, ...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:652 +0x40e
github.com/gomodule/redigo/redis.(*conn).Do(0xc0000d4dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x411a90, 0x45a76c)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:616 +0xa4
github.com/gomodule/redigo/redis.(*activeConn).Close(0xc00000e280, 0xc00009a0c0, 0xce8b01)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:427 +0x1da
github.com/gomodule/redigo/redis.PubSubConn.Close(...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pubsub.go:58
streaming-go/source/redis.(*source).Subscribe.func1(0xc00000e2a0, 0xc00009a120)
        /streaming-go/source/redis/redis.go:63 +0x25a
created by streaming-go/source/redis.(*source).Subscribe
        /streaming-go/source/redis/redis.go:58 +0x17a

goroutine 276 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fe57165e2d8, 0x72, 0xe63cc0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0003a2398, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003a2380, 0xc000117000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x253
net.(*netFD).Read(0xc0003a2380, 0xc000117000, 0x1000, 0x1000, 0x1000, 0x1000, 0xa0)
        /usr/local/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc0003ac010, 0xc000117000, 0x1000, 0x1000, 0xc00011701b, 0xc00023b9c8, 0x470774)
        /usr/local/go/src/net/net.go:184 +0xa1
bufio.(*Reader).fill(0xc0004f4180)
        /usr/local/go/src/bufio/bufio.go:100 +0x19a
bufio.(*Reader).ReadSlice(0xc0004f4180, 0xc0003a230a, 0x0, 0x0, 0x4274a0, 0x0, 0x18)
        /usr/local/go/src/bufio/bufio.go:359 +0x96
github.com/gomodule/redigo/redis.(*conn).readLine(0xc0000d5ea0, 0x0, 0x0, 0xc00023bc68, 0x4350ac, 0x4274a0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:431 +0x5a
github.com/gomodule/redigo/redis.(*conn).readReply(0xc0000d5ea0, 0x1, 0x1, 0xc0001d2d50, 0x0)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:504 +0x51
github.com/gomodule/redigo/redis.(*conn).DoWithTimeout(0xc0000d5ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x474280, 0xc0001f8300, 0xc00023be18, ...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:652 +0x40e
github.com/gomodule/redigo/redis.(*conn).Do(0xc0000d5ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4119f0, 0x7fe538012268)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/conn.go:616 +0xa4
github.com/gomodule/redigo/redis.(*activeConn).Close(0xc0000ba780, 0xc0000360c0, 0xce8a01)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:427 +0x1da
github.com/gomodule/redigo/redis.PubSubConn.Close(...)
        /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pubsub.go:58
streaming-go/source/redis.(*source).Subscribe.func1(0xc0000ba7a0, 0xc000036120)
        /streaming-go/source/redis/redis.go:63 +0x25a
created by streaming-go/source/redis.(*source).Subscribe
        /streaming-go/source/redis/redis.go:58 +0x17a
```

**Comment by stevenh** [comment]
The receive is blocking you would need to unsubscribe in `Stop`.

It would also be more idiomatic to close `s.q` instead of sending to it.

**Comment by Marsyyh** [comment]
@stevenh 
Thanks for your response. I tried your suggestion but nothing change.

From the stack I can tell the actual blocking part is https://github.com/gomodule/redigo/blob/master/redis/conn.go#L683. From what I read souce code here, redigo try to wait for all messages based on pending numbers. I don't know where it puts pending in. I guess it happens in `pubsub.Close()` since I saw it try to send some message before close.

I double looked my code, even though `s.conn.Receive()` is blocking, it could alway wait next for loop to close everything since my uploading tool will keep pub data into Redis topic.

Anything you can think of the `pending` is incorrect?

**Comment by stephenandwood** [comment]
Follow the pattern in the [pubsub example](https://godoc.org/github.com/gomodule/redigo/redis#example-PubSubConn).
        
```
type source struct {
	conn rd.PubSubConn
}

func (s *source) Subscribe(topic string) (<-chan []byte, error) {
	if err := s.conn.Subscribe(topic); err != nil {
		return nil, err
	}

	ch := make(chan []byte)

	go func() {
		defer s.conn.Close()
		close(ch)
		for {
			switch v := s.conn.Receive().(type) {
			case rd.Message:
				ch <- v.Data
			case redis.Subscription:
				if n.Count == 0 {
					// exit when no subscriptions
					return
				}
			}
		}
	}()

	return ch, nil
}

func (s *source) Stop() {
	s.conn.Unsubscribe() // unsubscribe from all channels
}
```

**Comment by Marsyyh** [comment]
@stephenandwood 
Thanks for suggestion. I modify it with `defer close(ch)` otherwise it will get nothing since ch is closed immediately.

I will still have exactly the same goroutine leak but this time it will leak 100% on a new connection.

Also, I want mention I can't return with `v.Count == 0` since it might have multiple sub to same topic. Also even error happens, I still can't return. That's why I need a return chan.

**Comment by stephenandwood** [comment]
Yes, it should be `defer close(ch)`. 

The Unsubscribe method sends the UNSUBSCRIBE command as the documentation states.  UNSUBSCRIBE with no arguments unsubscribes all Redis channels associated with the connection.

My suggested program will leak if the goroutine does not return when the subscription count drops to zero.   

There are no subscriptions on the connection when v.Count == 0.  What is the reason for continuing the receive loop with no subscriptions?

Errors are fatal to the connection.  If the application does not return on error, then the goroutine will spin in a tight loop processing error returns.

**Comment by stevenh** [comment]
I would change @stephenandwood example:
1. To avoid multiple goroutines if `Subscribe` is called multiple times as that's not needed.
2. To setup a new connection if the first one fails.
