### ISSUE TITLE
Potential concurrency bug: panic: runtime error: slice bounds out of range [12:8]

### ISSUE THREAD

**Issue by Epenjehem** [gomodule/redigo#540]
### Problem
```
/var/log/abc/abc.error.log panic: runtime error: slice bounds out of range [12:8]
/var/log/abc/abc.error.log goroutine 2600 [running]:
/var/log/abc/abc.error.log bufio.(*Reader).ReadSlice(0xc0048535c0, 0xa, 0x7f88387c2030, 0xc002ce0d80, 0x4d7047, 0xc0030e5080, 0x0)
	/home/buildbot/.gvm/gos/go1.14.4/src/bufio/bufio.go:334 +0x230
var/log/abc/abc.error.log github.com/abc/abc/vendor/github.com/garyburd/redigo/redis.(*conn).readLine(0xc000cf3cc0, 0x26e0010, 0xc002ce0dd8, 0x542069, 0xc0030e5080, 0xbfeb89479c4dcf47)
	/share/dpkg-build/abc-build/src/github.com/abc/abc/vendor/github.com/garyburd/redigo/redis/conn.go:406 +0x38
/var/log/abc/abc.error.log github.com/abc/abc/vendor/github.com/garyburd/redigo/redis.(*conn).readReply(0xc000cf3cc0, 0xbfeb89479c4dcf47, 0x28f75c652, 0x4345bc0, 0x0)
	/share/dpkg-build/abc-build/src/github.com/abc/abc/vendor/github.com/garyburd/redigo/redis/conn.go:479 +0x2f
/var/log/abc/abc.error.log github.com/abc/abc/vendor/github.com/garyburd/redigo/redis.(*conn).Do(0xc000cf3cc0, 0x2613c24, 0x6, 0xc0035dc5b0, 0x1, 0x1, 0x10, 0x20d35c0, 0xc00514ca01, 0xc0035dc5b0)
	/share/dpkg-build/abc-build/src/github.com/abc/abc/vendor/github.com/garyburd/redigo/redis/conn.go:627 +0x12a
/var/log/abc/abc.error.log github.com/abc/abc/vendor/github.com/garyburd/redigo/redis.(*pooledConnection).Do(0xc0035d2700, 0x2613c24, 0x6, 0xc0035dc5b0, 0x1, 0x1, 0x4000101, 0x6edbbe, 0xffffffffffffff01, 0xc002ce0f50)
	/share/dpkg-build/abc-build/src/github.com/abc/abc/vendor/github.com/garyburd/redigo/redis/pool.go:418 +0xc5
```

We encountered strange panic log when the buffer trying to slice with strange index range `runtime error: slice bounds out of range [12:8]`

How we use:
```go

redisClient, err := getRedisConnection() // connection is initialized using redigo.Pool
if err != nil {
    return false, err
}

defer redisClient.Close()

...

go func() {
    var tempErr error
    isExist, tempErr = redisClient.Exists(key)
    chanErr <- tempErr
}()

select {
case <-ctx.Done():
    return false, ctx.Err()
case err := <-chanErr:
    if err != nil {
        return false, err
    }
    return isExist, nil
}
```
```go
// our wrapper
func (cx Connectionx) Exists(key string) (bool, error) {
	cx.mu.Lock()
	defer cx.mu.Unlock()

	return redigo.Bool(cx.Conn.Do("EXISTS", key))
}
```

Library version: `github.com/garyburd/redigo v1.3.0`
Go version: `1.14.4`
OS: `Linux`

**Comment by stevenh** [comment]
v1.3.0 is very old please update to the latest version and see if you can still reproduce

**Comment by learnavi** [comment]
I also got similar error in v1.8.3

```
panic: runtime error: slice bounds out of range [12:8]

goroutine 369318 [running]:
bufio.(*Reader).ReadSlice(0xc0007908a0, 0x100a, 0x4c, 0xc000881a68, 0x4d6e0d, 0xc00078e500, 0xc000881a00)
	/opt/hostedtoolcache/go/1.15.6/x64/src/bufio/bufio.go:335 +0x225
github.com/gomodule/redigo/redis.(*conn).readLine(0xc00071da40, 0x11aa8a0, 0xc000881b28, 0x629309, 0xc00078e500, 0x0)
	/home/runner/go/pkg/mod/github.com/gomodule/redigo@v1.8.3/redis/conn.go:518 +0x49
github.com/gomodule/redigo/redis.(*conn).readReply(0xc00071da40, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/gomodule/redigo@v1.8.3/redis/conn.go:598 +0x2f
github.com/gomodule/redigo/redis.(*conn).DoWithTimeout(0xc00071da40, 0x0, 0x1161167, 0x9, 0xc00028db20, 0x2, 0x2, 0x10, 0xfd1680, 0x1, ...)
	/home/runner/go/pkg/mod/github.com/gomodule/redigo@v1.8.3/redis/conn.go:759 +0x15d
github.com/gomodule/redigo/redis.(*conn).Do(0xc00071da40, 0x1161167, 0x9, 0xc00028db20, 0x2, 0x2, 0x450987, 0x0, 0xc000881cb0, 0x3)
	/home/runner/go/pkg/mod/github.com/gomodule/redigo@v1.8.3/redis/conn.go:710 +0x73
```

How we use:
```golang
	isMember, err := redis.Bool(rdb.Do("SISMEMBER", key, value))
	if err != nil {
		return false, fmt.Errorf("failed to send SISMEMBER command: %w", err)
	}

	return isMember, nil
```

**Comment by stevenh** [comment]
Looks like you're opening just a single connection then potentially using that single connection from multiple `goroutines` which is not safe. Each operation should use it's own connection from a pool. See the documentation for an example of how to do this.

**Comment by learnavi** [comment]
Yep! I think that's the problem! Thanks @stevenh for the answers
