### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Gutyerrez** [gomodule/redigo#560]
My redis connection file

```go
package redis

import (
	"fmt"
	"github.com/gomodule/redigo/redis"
	"net/hyren/nyrah/environment"
	"time"

	DatabaseProviders "net/hyren/nyrah/providers/databases"
)

type RedisDatabaseProvider struct {
	DatabaseProviders.IDatabaseProvider

	pool *redis.Pool
}

func (redisDatabaseProvider RedisDatabaseProvider) Prepare() {
	var main = environment.Get("databases").(map[string]interface{})["redis"].(map[string]interface{})["main"].(map[string]interface{})

	var host = main["host"].(string)
	var port = int(main["port"].(float64))
	var password = main["password"].(string)

	redisDatabaseProvider.pool = &redis.Pool{
		MaxIdle:     3,
		IdleTimeout: 240 * time.Second,
		Dial: func() (redis.Conn, error) {
			fmt.Printf("Connecting to redis database (%s:%d)...\n", host, port)

			c, err := redis.Dial("tcp", fmt.Sprintf("%s:%d", host, port))

			if err != nil {
				fmt.Println(err)
			}

			if _, err := c.Do("AUTH", password); err != nil {
				fmt.Println("Autho:", err)

				_ = c.Close()

				return nil, err
			}

			if _, err := c.Do("SELECT", "0"); err != nil {
				fmt.Println("Select:", err)

				_ = c.Close()

				return nil, err
			}

			return c, err
		},
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			_, err := c.Do("PING")

			fmt.Println("Ping:", err)

			return err
		},
	}

	response, err := redisDatabaseProvider.pool.Get().Do("GET", "applications:proxy-1")

	if err != nil {
		fmt.Println("Test:", err)
	} else {
		fmt.Println("Response:", response)
	}
}

func (redisDatabaseProvider RedisDatabaseProvider) Provide() *redis.Pool {
	return redisDatabaseProvider.pool
}
```

Generated error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6429f7]

goroutine 19 [running]:
github.com/gomodule/redigo/redis.(*Pool).waitVacantConn(0x0, 0x70ee90, 0xc0000160d0, 0xc000122000, 0x31, 0x40)
        /home/runner/go/pkg/mod/github.com/gomodule/redigo@v1.8.4/redis/pool.go:357 +0x37
github.com/gomodule/redigo/redis.(*Pool).GetContext(0x0, 0x70ee90, 0xc0000160d0, 0x0, 0x0, 0x6a0200, 0x2)
        /home/runner/go/pkg/mod/github.com/gomodule/redigo@v1.8.4/redis/pool.go:200 +0x5a
github.com/gomodule/redigo/redis.(*Pool).Get(...)
        /home/runner/go/pkg/mod/github.com/gomodule/redigo@v1.8.4/redis/pool.go:186
net/hyren/nyrah/applications/status/proxy.GetOnlinePlayers(0x0)
        /home/runner/work/nyrah/nyrah/src/applications/status/proxy/ProxyStatus.go:81 +0xb3
net/hyren/nyrah/misc/packets.HandlePackets(0xc0001a6050, 0x70baa0, 0x8831c0, 0x0, 0x0)
        /home/runner/work/nyrah/nyrah/src/misc/packets/PacketHandler.go:45 +0x94f
net/hyren/nyrah/minecraft.(*Server).handleConnection(0xc000194120, 0xc0001a6050)
        /home/runner/work/nyrah/nyrah/src/minecraft/server.go:74 +0x199
created by net/hyren/nyrah/minecraft.(*Server).ListenAndServe
        /home/runner/work/nyrah/nyrah/src/minecraft/server.go:50 +0x2d7
```

ProxyStatus file:

```go
package proxy

import (
	"encoding/json"
	"fmt"
	"github.com/gomodule/redigo/redis"
	"net"
	"net/hyren/nyrah/cache/local"
	"time"

	NyrahProvider "net/hyren/nyrah/misc/providers"
)

func GetApplicationOnlinePlayers(application string) (int, error) {
	redisConnection := NyrahProvider.REDIS_MAIN.Provide().Get()

	var bytes, err = redis.Bytes(
		redisConnection.Do("GET", fmt.Sprintf("applications:%s", application)),
	)

	defer redisConnection.Close()

	if err != nil {
		return 0, err
	}

	var data map[string]interface{}

	err = json.Unmarshal(bytes, &data)

	if err != nil {
		return 0, err
	}
	return int(data["online_players"].(float64)), nil
}

func GetApplicationAddress(application string) (string, error) {
	redisConnection := NyrahProvider.REDIS_MAIN.Provide().Get()

	var bytes, err = redis.Bytes(
		redisConnection.Do("GET", fmt.Sprintf("applications:%s", application)),
	)

	defer redisConnection.Close()

	if err != nil {
		return "", err
	}

	var data map[string]interface{}

	err = json.Unmarshal(bytes, &data)

	if err != nil {
		return "", err
	}

	address := data["inet_socket_address"].(map[string]interface{})

	return fmt.Sprintf(
		"%s:%d",
		address["host"].(string),
		int(address["port"].(float64)),
	), nil
}

func IsProxyOnline(server string) bool {
	_, err := net.Dial("tcp", server)

	if err != nil {
		return false
	}

	return true
}

func GetOnlinePlayers() int {
	onlinePlayers, found := local.CACHE.Get("online_players")

	if !found {
		redisConnection := NyrahProvider.REDIS_MAIN.Provide().Get() // line 81

		cursor := 0

		for ok := true; ok; ok = cursor != 0 {
			result, err := redis.Values(
				redisConnection.Do("SCAN", cursor, "MATCH", "users:*"),
			)

			defer redisConnection.Close()

			if err != nil {
				fmt.Println(err)

				return 0
			}

			cursor, _ = redis.Int(result[0], nil)
			keys, _ := redis.Strings(result[1], nil)

			onlinePlayers = onlinePlayers.(int) + len(keys)
		}

		local.CACHE.Set("online_players", onlinePlayers, 1*time.Second)
	}

	return onlinePlayers.(int)
}
```

**Comment by stevenh** [comment]
Here's some comments
* You creating a new pool for each call to `Prepare` - This is likely the cause of your panic
* `GetOnlinePlayers` you have multiple `redisConnection.Close()` calls as it's in the loop
